#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cat data/expire_tiles/expire_tiles.tiles > data/expire_tiles/expire_tiles_zoom.tiles

while read line; do
	zoom=`echo $line | cut -d '/' -f 1`

	# Exit if we have processed all zooms levels
	if [ "$zoom" -eq "0" ]; then
		break;
	fi

	x=`echo $line | cut -d '/' -f 2`
	y=`echo $line | cut -d '/' -f 3`

	# Write upper tile for this tile
	echo "$((zoom-1))/$((x/2))/$((y/2))" >> data/expire_tiles/expire_tiles_zoom.tiles
done < data/expire_tiles/expire_tiles_zoom.tiles

# Sort and deduplicate tiles
cat data/expire_tiles/expire_tiles_zoom.tiles | sort | uniq > data/expire_tiles/expire_tiles.tiles
rm -f data/expire_tiles/expire_tiles_zoom.tiles
