#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

wget https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf data/

make clean
make
docker-compose up -d postgres
make forced-clean-sql
docker-compose run --rm import-osm
docker-compose run --rm import-sql
make psql-analyze
