#!/bin/bash

make

docker run --name indoorequal-db --env POSTGRES_PASSWORD=postgres --detach indoorequal/postgis

docker run --rm \
       --link indoorequal-db:db \
       --volume $PWD:/tests \
       --env PGPASSWORD=postgres \
       postgres psql --host=db --username postgres postgres \
       -f /tests/layers/common/table_schema.sql

docker run \
       --rm \
       --link indoorequal-db:db \
       -e POSTGRES_DB=postgres \
       -e POSTGRES_USER=postgres \
       -e POSTGRES_PASSWORD=postgres \
       -e POSTGRES_HOST=db \
       --volume $PWD/build:/sql \
       indoorequal/openmaptiles-tools import_sql.sh

docker run --interactive --tty --rm \
       --name indoorequal-pgtap \
       --link indoorequal-db:db \
       --env PASSWORD=postgres \
       --env TESTS=/tests/layers/**/*_test.sql \
       --env DATABASE=postgres \
       --volume $PWD:/tests \
       hbpmip/pgtap
